
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 27
#define YY_END_OF_BUFFER 28
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[378] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   28,   25,   26,    1,   27,    2,
        3,    6,    7,    8,    9,   12,   13,   15,   14,   16,
       17,   19,   19,   19,   24,    4,    5,   10,   11,   21,
       22,   23,   27,   20,    0,   19,   20,   18,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    2,    1,    1,    1,    1,    1,    5,
        6,    1,    1,    7,    8,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    9,    1,    1,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
        1,   11,    1,    1,    1,    1,   12,   12,   12,   12,

       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   13,   14,   15,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[16] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[380] =
    {   0,
        0,    1,  993,  992,    0,    1,   13,    0,    6,    7,
      997,  996,    2,   17,   54,   53,   55,   54,   18,    0,
       57,   56,    0,    0,   30,    0,   45,    0,   54,    0,
       17,   15,    0,    0,   14, 1007, 1007, 1007, 1007, 1007,
     1007, 1007, 1007, 1007, 1007, 1007, 1007, 1007, 1007, 1007,
     1007,   60,   63,   66, 1007, 1007, 1007, 1007, 1007, 1007,
     1007, 1007,    4,   69,    0,    0,    0, 1007,   72,   75,
       78,   81,   84,   87,   90,   93,   96,   99,  102,  105,
      108,  111,  114,  117,  120,  123,  126,  129,  132,  135,
      138,  141,  144,  147,  150,  153,  156,  159,  162,  165,

      168,  171,  174,  177,  180,  183,  186,  189,  192,  195,
      198,  201,  204,  207,  210,  213,  216,  219,  222,  225,
      228,  231,  234,  237,  240,  243,  246,  249,  252,  255,
      258,  261,  264,  267,  270,  273,  276,  279,  282,  285,
      288,  291,  294,  297,  300,  303,  306,  309,  312,  315,
      318,  321,  324,  327,  330,  333,  336,  339,  342,  345,
      348,  351,  354,  357,  360,  363,  366,  369,  372,  375,
      378,  381,  384,  387,  390,  393,  396,  399,  402,  405,
      408,  411,  414,  417,  420,  423,  426,  429,  432,  435,
      438,  441,  444,  447,  450,  453,  456,  459,  462,  465,

      468,  471,  474,  477,  480,  483,  486,  489,  492,  495,
      498,  501,  504,  507,  510,  513,  516,  519,  522,  525,
      528,  531,  534,  537,  540,  543,  546,  549,  552,  555,
      558,  561,  564,  567,  570,  573,  576,  579,  582,  585,
      588,  591,  594,  597,  600,  603,  606,  609,  612,  615,
      618,  621,  624,  627,  630,  633,  636,  639,  642,  645,
      648,  651,  654,  657,  660,  663,  666,  669,  672,  675,
      678,  681,  684,  687,  690,  693,  696,  699,  702,  705,
      708,  711,  714,  717,  720,  723,  726,  729,  732,  735,
      738,  741,  744,  747,  750,  753,  756,  759,  762,  765,

      768,  771,  774,  777,  780,  783,  786,  789,  792,  795,
      798,  801,  804,  807,  810,  813,  816,  819,  822,  825,
      828,  831,  834,  837,  840,  843,  846,  849,  852,  855,
      858,  861,  864,  867,  870,  873,  876,  879,  882,  885,
      888,  891,  894,  897,  900,  903,  906,  909,  912,  915,
      918,  921,  924,  927,  930,  933,  936,  939,  942,  945,
      948,  951,  954,  957,  960,  963,  966,  969,  972,  975,
      978,  981,  984,  987,  990, 1007, 1007,    1,    0
    } ;

static yyconst flex_int16_t yy_def[380] =
    {   0,
      378,  378,  379,  379,  379,  379,  379,    7,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,   19,
      379,  379,  379,  379,  377,   25,  377,   27,  379,   29,
      379,  379,  379,  379,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,   64,   64,   64,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,

      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,    0,  377,  377
    } ;

static yyconst flex_int16_t yy_nxt[1023] =
    {   0,
       39,   36,   37,   37,   38,   38,  377,  377,   48,   41,
       41,   49,   68,  377,   42,   42,   43,   45,   45,   43,
       46,   46,   63,   48,   63,   44,   49,   52,   53,   54,
       56,   39,   56,   39,   39,   39,   57,   56,   56,   56,
       56,   56,   56,   39,   42,   58,   39,   58,   39,   39,
       39,   59,   58,   58,   58,   58,   58,   58,   39,   46,
       60,   55,   55,   51,   51,   50,   50,   61,   62,   64,
       65,   66,   65,   65,   65,   66,   65,   67,   69,   69,
       69,   70,   70,   70,   71,   71,   71,   72,   72,   72,
       73,   73,   73,   74,   74,   74,   75,   75,   75,   76,

       76,   76,   77,   77,   77,   78,   78,   78,   79,   79,
       79,   80,   80,   80,   81,   81,   81,   82,   82,   82,
       83,   83,   83,   84,   84,   84,   85,   85,   85,   86,
       86,   86,   87,   87,   87,   88,   88,   88,   89,   89,
       89,   90,   90,   90,   91,   91,   91,   92,   92,   92,
       93,   93,   93,   94,   94,   94,   95,   95,   95,   96,
       96,   96,   97,   97,   97,   98,   98,   98,   99,   99,
       99,  100,  100,  100,  101,  101,  101,  102,  102,  102,
      103,  103,  103,  104,  104,  104,  105,  105,  105,  106,
      106,  106,  107,  107,  107,  108,  108,  108,  109,  109,

      109,  110,  110,  110,  111,  111,  111,  112,  112,  112,
      113,  113,  113,  114,  114,  114,  115,  115,  115,  116,
      116,  116,  117,  117,  117,  118,  118,  118,  119,  119,
      119,  120,  120,  120,  121,  121,  121,  122,  122,  122,
      123,  123,  123,  124,  124,  124,  125,  125,  125,  126,
      126,  126,  127,  127,  127,  128,  128,  128,  129,  129,
      129,  130,  130,  130,  131,  131,  131,  132,  132,  132,
      133,  133,  133,  134,  134,  134,  135,  135,  135,  136,
      136,  136,  137,  137,  137,  138,  138,  138,  139,  139,
      139,  140,  140,  140,  141,  141,  141,  142,  142,  142,

      143,  143,  143,  144,  144,  144,  145,  145,  145,  146,
      146,  146,  147,  147,  147,  148,  148,  148,  149,  149,
      149,  150,  150,  150,  151,  151,  151,  152,  152,  152,
      153,  153,  153,  154,  154,  154,  155,  155,  155,  156,
      156,  156,  157,  157,  157,  158,  158,  158,  159,  159,
      159,  160,  160,  160,  161,  161,  161,  162,  162,  162,
      163,  163,  163,  164,  164,  164,  165,  165,  165,  166,
      166,  166,  167,  167,  167,  168,  168,  168,  169,  169,
      169,  170,  170,  170,  171,  171,  171,  172,  172,  172,
      173,  173,  173,  174,  174,  174,  175,  175,  175,  176,

      176,  176,  177,  177,  177,  178,  178,  178,  179,  179,
      179,  180,  180,  180,  181,  181,  181,  182,  182,  182,
      183,  183,  183,  184,  184,  184,  185,  185,  185,  186,
      186,  186,  187,  187,  187,  188,  188,  188,  189,  189,
      189,  190,  190,  190,  191,  191,  191,  192,  192,  192,
      193,  193,  193,  194,  194,  194,  195,  195,  195,  196,
      196,  196,  197,  197,  197,  198,  198,  198,  199,  199,
      199,  200,  200,  200,  201,  201,  201,  202,  202,  202,
      203,  203,  203,  204,  204,  204,  205,  205,  205,  206,
      206,  206,  207,  207,  207,  208,  208,  208,  209,  209,

      209,  210,  210,  210,  211,  211,  211,  212,  212,  212,
      213,  213,  213,  214,  214,  214,  215,  215,  215,  216,
      216,  216,  217,  217,  217,  218,  218,  218,  219,  219,
      219,  220,  220,  220,  221,  221,  221,  222,  222,  222,
      223,  223,  223,  224,  224,  224,  225,  225,  225,  226,
      226,  226,  227,  227,  227,  228,  228,  228,  229,  229,
      229,  230,  230,  230,  231,  231,  231,  232,  232,  232,
      233,  233,  233,  234,  234,  234,  235,  235,  235,  236,
      236,  236,  237,  237,  237,  238,  238,  238,  239,  239,
      239,  240,  240,  240,  241,  241,  241,  242,  242,  242,

      243,  243,  243,  244,  244,  244,  245,  245,  245,  246,
      246,  246,  247,  247,  247,  248,  248,  248,  249,  249,
      249,  250,  250,  250,  251,  251,  251,  252,  252,  252,
      253,  253,  253,  254,  254,  254,  255,  255,  255,  256,
      256,  256,  257,  257,  257,  258,  258,  258,  259,  259,
      259,  260,  260,  260,  261,  261,  261,  262,  262,  262,
      263,  263,  263,  264,  264,  264,  265,  265,  265,  266,
      266,  266,  267,  267,  267,  268,  268,  268,  269,  269,
      269,  270,  270,  270,  271,  271,  271,  272,  272,  272,
      273,  273,  273,  274,  274,  274,  275,  275,  275,  276,

      276,  276,  277,  277,  277,  278,  278,  278,  279,  279,
      279,  280,  280,  280,  281,  281,  281,  282,  282,  282,
      283,  283,  283,  284,  284,  284,  285,  285,  285,  286,
      286,  286,  287,  287,  287,  288,  288,  288,  289,  289,
      289,  290,  290,  290,  291,  291,  291,  292,  292,  292,
      293,  293,  293,  294,  294,  294,  295,  295,  295,  296,
      296,  296,  297,  297,  297,  298,  298,  298,  299,  299,
      299,  300,  300,  300,  301,  301,  301,  302,  302,  302,
      303,  303,  303,  304,  304,  304,  305,  305,  305,  306,
      306,  306,  307,  307,  307,  308,  308,  308,  309,  309,

      309,  310,  310,  310,  311,  311,  311,  312,  312,  312,
      313,  313,  313,  314,  314,  314,  315,  315,  315,  316,
      316,  316,  317,  317,  317,  318,  318,  318,  319,  319,
      319,  320,  320,  320,  321,  321,  321,  322,  322,  322,
      323,  323,  323,  324,  324,  324,  325,  325,  325,  326,
      326,  326,  327,  327,  327,  328,  328,  328,  329,  329,
      329,  330,  330,  330,  331,  331,  331,  332,  332,  332,
      333,  333,  333,  334,  334,  334,  335,  335,  335,  336,
      336,  336,  337,  337,  337,  338,  338,  338,  339,  339,
      339,  340,  340,  340,  341,  341,  341,  342,  342,  342,

      343,  343,  343,  344,  344,  344,  345,  345,  345,  346,
      346,  346,  347,  347,  347,  348,  348,  348,  349,  349,
      349,  350,  350,  350,  351,  351,  351,  352,  352,  352,
      353,  353,  353,  354,  354,  354,  355,  355,  355,  356,
      356,  356,  357,  357,  357,  358,  358,  358,  359,  359,
      359,  360,  360,  360,  361,  361,  361,  362,  362,  362,
      363,  363,  363,  364,  364,  364,  365,  365,  365,  366,
      366,  366,  367,  367,  367,  368,  368,  368,  369,  369,
      369,  370,  370,  370,  371,  371,  371,  372,  372,  372,
      373,  373,  373,  374,  374,  374,  375,  375,  375,  376,

      376,  376,   47,   47,   40,   40,   35,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377
    } ;

static yyconst flex_int16_t yy_chk[1023] =
    {   0,
      379,  378,    1,    2,    1,    2,    0,    0,   13,    5,
        6,   13,   63,   35,    5,    6,    7,    9,   10,    7,
        9,   10,   32,   14,   31,    7,   14,   19,   19,   19,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       29,   22,   21,   18,   17,   16,   15,   29,   29,   52,
       52,   52,   53,   53,   53,   54,   54,   54,   64,   64,
       64,   69,   69,   69,   70,   70,   70,   71,   71,   71,
       72,   72,   72,   73,   73,   73,   74,   74,   74,   75,

       75,   75,   76,   76,   76,   77,   77,   77,   78,   78,
       78,   79,   79,   79,   80,   80,   80,   81,   81,   81,
       82,   82,   82,   83,   83,   83,   84,   84,   84,   85,
       85,   85,   86,   86,   86,   87,   87,   87,   88,   88,
       88,   89,   89,   89,   90,   90,   90,   91,   91,   91,
       92,   92,   92,   93,   93,   93,   94,   94,   94,   95,
       95,   95,   96,   96,   96,   97,   97,   97,   98,   98,
       98,   99,   99,   99,  100,  100,  100,  101,  101,  101,
      102,  102,  102,  103,  103,  103,  104,  104,  104,  105,
      105,  105,  106,  106,  106,  107,  107,  107,  108,  108,

      108,  109,  109,  109,  110,  110,  110,  111,  111,  111,
      112,  112,  112,  113,  113,  113,  114,  114,  114,  115,
      115,  115,  116,  116,  116,  117,  117,  117,  118,  118,
      118,  119,  119,  119,  120,  120,  120,  121,  121,  121,
      122,  122,  122,  123,  123,  123,  124,  124,  124,  125,
      125,  125,  126,  126,  126,  127,  127,  127,  128,  128,
      128,  129,  129,  129,  130,  130,  130,  131,  131,  131,
      132,  132,  132,  133,  133,  133,  134,  134,  134,  135,
      135,  135,  136,  136,  136,  137,  137,  137,  138,  138,
      138,  139,  139,  139,  140,  140,  140,  141,  141,  141,

      142,  142,  142,  143,  143,  143,  144,  144,  144,  145,
      145,  145,  146,  146,  146,  147,  147,  147,  148,  148,
      148,  149,  149,  149,  150,  150,  150,  151,  151,  151,
      152,  152,  152,  153,  153,  153,  154,  154,  154,  155,
      155,  155,  156,  156,  156,  157,  157,  157,  158,  158,
      158,  159,  159,  159,  160,  160,  160,  161,  161,  161,
      162,  162,  162,  163,  163,  163,  164,  164,  164,  165,
      165,  165,  166,  166,  166,  167,  167,  167,  168,  168,
      168,  169,  169,  169,  170,  170,  170,  171,  171,  171,
      172,  172,  172,  173,  173,  173,  174,  174,  174,  175,

      175,  175,  176,  176,  176,  177,  177,  177,  178,  178,
      178,  179,  179,  179,  180,  180,  180,  181,  181,  181,
      182,  182,  182,  183,  183,  183,  184,  184,  184,  185,
      185,  185,  186,  186,  186,  187,  187,  187,  188,  188,
      188,  189,  189,  189,  190,  190,  190,  191,  191,  191,
      192,  192,  192,  193,  193,  193,  194,  194,  194,  195,
      195,  195,  196,  196,  196,  197,  197,  197,  198,  198,
      198,  199,  199,  199,  200,  200,  200,  201,  201,  201,
      202,  202,  202,  203,  203,  203,  204,  204,  204,  205,
      205,  205,  206,  206,  206,  207,  207,  207,  208,  208,

      208,  209,  209,  209,  210,  210,  210,  211,  211,  211,
      212,  212,  212,  213,  213,  213,  214,  214,  214,  215,
      215,  215,  216,  216,  216,  217,  217,  217,  218,  218,
      218,  219,  219,  219,  220,  220,  220,  221,  221,  221,
      222,  222,  222,  223,  223,  223,  224,  224,  224,  225,
      225,  225,  226,  226,  226,  227,  227,  227,  228,  228,
      228,  229,  229,  229,  230,  230,  230,  231,  231,  231,
      232,  232,  232,  233,  233,  233,  234,  234,  234,  235,
      235,  235,  236,  236,  236,  237,  237,  237,  238,  238,
      238,  239,  239,  239,  240,  240,  240,  241,  241,  241,

      242,  242,  242,  243,  243,  243,  244,  244,  244,  245,
      245,  245,  246,  246,  246,  247,  247,  247,  248,  248,
      248,  249,  249,  249,  250,  250,  250,  251,  251,  251,
      252,  252,  252,  253,  253,  253,  254,  254,  254,  255,
      255,  255,  256,  256,  256,  257,  257,  257,  258,  258,
      258,  259,  259,  259,  260,  260,  260,  261,  261,  261,
      262,  262,  262,  263,  263,  263,  264,  264,  264,  265,
      265,  265,  266,  266,  266,  267,  267,  267,  268,  268,
      268,  269,  269,  269,  270,  270,  270,  271,  271,  271,
      272,  272,  272,  273,  273,  273,  274,  274,  274,  275,

      275,  275,  276,  276,  276,  277,  277,  277,  278,  278,
      278,  279,  279,  279,  280,  280,  280,  281,  281,  281,
      282,  282,  282,  283,  283,  283,  284,  284,  284,  285,
      285,  285,  286,  286,  286,  287,  287,  287,  288,  288,
      288,  289,  289,  289,  290,  290,  290,  291,  291,  291,
      292,  292,  292,  293,  293,  293,  294,  294,  294,  295,
      295,  295,  296,  296,  296,  297,  297,  297,  298,  298,
      298,  299,  299,  299,  300,  300,  300,  301,  301,  301,
      302,  302,  302,  303,  303,  303,  304,  304,  304,  305,
      305,  305,  306,  306,  306,  307,  307,  307,  308,  308,

      308,  309,  309,  309,  310,  310,  310,  311,  311,  311,
      312,  312,  312,  313,  313,  313,  314,  314,  314,  315,
      315,  315,  316,  316,  316,  317,  317,  317,  318,  318,
      318,  319,  319,  319,  320,  320,  320,  321,  321,  321,
      322,  322,  322,  323,  323,  323,  324,  324,  324,  325,
      325,  325,  326,  326,  326,  327,  327,  327,  328,  328,
      328,  329,  329,  329,  330,  330,  330,  331,  331,  331,
      332,  332,  332,  333,  333,  333,  334,  334,  334,  335,
      335,  335,  336,  336,  336,  337,  337,  337,  338,  338,
      338,  339,  339,  339,  340,  340,  340,  341,  341,  341,

      342,  342,  342,  343,  343,  343,  344,  344,  344,  345,
      345,  345,  346,  346,  346,  347,  347,  347,  348,  348,
      348,  349,  349,  349,  350,  350,  350,  351,  351,  351,
      352,  352,  352,  353,  353,  353,  354,  354,  354,  355,
      355,  355,  356,  356,  356,  357,  357,  357,  358,  358,
      358,  359,  359,  359,  360,  360,  360,  361,  361,  361,
      362,  362,  362,  363,  363,  363,  364,  364,  364,  365,
      365,  365,  366,  366,  366,  367,  367,  367,  368,  368,
      368,  369,  369,  369,  370,  370,  370,  371,  371,  371,
      372,  372,  372,  373,  373,  373,  374,  374,  374,  375,

      375,  375,   12,   11,    4,    3,  377,  377,  377,  377,
      377,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "Gramatica.l"
#line 2 "Gramatica.l"
#include <ctype.h>
#include <stdlib.h>
#include <stdio.h>
#include "./TPE/structs.h"

gramatica_struct * gramatica;
char leftPart=0;
















#line 827 "lex.yy.c"

#define INITIAL 0
#define DEFINITION 1
#define TERMINALS 2
#define ENDTERMINALS 3
#define NONTERMINALS 4
#define ENDNONTERMINALS 5
#define INITIALS 6
#define ENDINITIALS 7
#define LEFTPRODUCTION 8
#define RIGHTPRODUCTION 9
#define ENDPRODUCTIONS 10
#define ENDDEFINITION 11
#define TERMSEPARATOR 12
#define NONTERMSEPARATOR 13
#define PRODSEPARATOR 14
#define ARROW 15
#define ERROR 16

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 27 "Gramatica.l"


#line 1033 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 378 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1007 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "Gramatica.l"
BEGIN(DEFINITION);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "Gramatica.l"
;BEGIN(TERMINALS);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "Gramatica.l"
{addTerminal(*yytext);}BEGIN(TERMSEPARATOR);
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 32 "Gramatica.l"
{reportError("terminales",yytext);}; BEGIN(ERROR);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "Gramatica.l"
BEGIN(TERMINALS);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "Gramatica.l"
BEGIN(ENDTERMINALS);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "Gramatica.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "Gramatica.l"
BEGIN(NONTERMINALS);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "Gramatica.l"
{addNonTerminal(*yytext);}BEGIN(NONTERMSEPARATOR);
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 38 "Gramatica.l"
{reportError("no terminales", yytext);}; BEGIN(ERROR);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "Gramatica.l"
BEGIN(NONTERMINALS);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "Gramatica.l"
BEGIN(ENDNONTERMINALS);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "Gramatica.l"
;BEGIN(INITIALS);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "Gramatica.l"
{addInitialSymbol(*yytext);};
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "Gramatica.l"
;BEGIN(ENDINITIALS);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "Gramatica.l"
BEGIN(LEFTPRODUCTION);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "Gramatica.l"
{getProductionLeftPart(*yytext);}; BEGIN(ARROW);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "Gramatica.l"
BEGIN(RIGHTPRODUCTION);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "Gramatica.l"
{getProduction(yytext,yyleng);}; BEGIN(PRODSEPARATOR);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "Gramatica.l"
{reportError("una parte derecha de producciones", yytext);}; BEGIN(ERROR);	
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "Gramatica.l"
BEGIN(LEFTPRODUCTION);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "Gramatica.l"
BEGIN(RIGHTPRODUCTION);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "Gramatica.l"
BEGIN(ENDPRODUCTIONS);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "Gramatica.l"
BEGIN(ENDDEFINITION);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "Gramatica.l"
;
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 54 "Gramatica.l"
;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 57 "Gramatica.l"
ECHO;
	YY_BREAK
#line 1254 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(DEFINITION):
case YY_STATE_EOF(TERMINALS):
case YY_STATE_EOF(ENDTERMINALS):
case YY_STATE_EOF(NONTERMINALS):
case YY_STATE_EOF(ENDNONTERMINALS):
case YY_STATE_EOF(INITIALS):
case YY_STATE_EOF(ENDINITIALS):
case YY_STATE_EOF(LEFTPRODUCTION):
case YY_STATE_EOF(RIGHTPRODUCTION):
case YY_STATE_EOF(ENDPRODUCTIONS):
case YY_STATE_EOF(ENDDEFINITION):
case YY_STATE_EOF(TERMSEPARATOR):
case YY_STATE_EOF(NONTERMSEPARATOR):
case YY_STATE_EOF(PRODSEPARATOR):
case YY_STATE_EOF(ARROW):
case YY_STATE_EOF(ERROR):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 378 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 378 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 377);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 57 "Gramatica.l"



int
main(int argc, char* argv[]){
int err,pid;
FILE * file;
	FILE* fileToOpen= fopen(argv[1], "r");
	if(fileToOpen== NULL){
		printf("Error al abrir el archivo\n");
		return 1;
	}
	else
		yyin=fileToOpen;
	
	createGramatica();	
	yylex();
	/*
	eliminateInproductive();
	eliminateUnreach();
	left_eliminateUnitaries();
	eliminateUnreach();
	
	if ( isLeft() == 1 ){
		left_normalize();
	}else if ( isLeft() == 0){
		right_normalize();
	}else{
		printf("Error en la gramatica, no corresponde a ningún tipo conocido\n");
		return 0;
	}
	*/
	printf("La gramatica es Correcta\n\n");		
	showTerminalSymbols();
	showNonTerminalSymbols();
	showInitialSymbol();
	showProductionSymbols();
	
	//Armo el Archivo;
	makeDotFile(file);
	
	//Grafico
	if ( (pid = fork()) < 0 ){
			perror("fork");
			exit(1);
	}
	if (pid == 0){
			system(strcat(argv[2]," -Tpng file.dot -o graph.png"));
			exit(1);
	}
}

int addProductions(char leftside, char rightside1, char rightside2){
	int size = gramatica->production_function->size;
	gramatica->production_function->productions[size].leftsimbol = leftside;
	gramatica->production_function->productions[size].rightsimbols[0] = rightside1;
	gramatica->production_function->productions[size].rightsimbols[1] = rightside2;
	gramatica->production_function->size = size + 1;
	return 1;
}
int isLeft(){
	int resp = -1;
	int k;
	
	for (k = 0; k < gramatica->production_function->size; k++){
			if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
				char left = gramatica->production_function->productions[k].leftsimbol;
				char sright = gramatica->production_function->productions[k].rightsimbols[1];
				char fright = gramatica->production_function->productions[k].rightsimbols[0];
			
				if ( (fright >= 'a' && fright <= 'z') && sright != 0 && resp == -1){
					resp = 1;
				}else if( (fright >= 'A' && fright <= 'Z') && sright != 0 && resp == -1){
					resp = 0;
				}else if( (fright >= 'A' && fright <= 'Z') && sright != 0 && resp == 1){
						resp = -1;
						return resp;
				}else if( (fright >= 'a' && fright <= 'z') && sright != 0 && resp == 0){
							resp = -1;
							return resp;
				}
			}
	}
	
	return resp;
}

void right_normalize(){
	int j,k,i;
	
	for (k = 0; k < gramatica->production_function->size; k++){
			if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
				char left = gramatica->production_function->productions[k].leftsimbol;
				char sright = gramatica->production_function->productions[k].rightsimbols[1];
				char fright = gramatica->production_function->productions[k].rightsimbols[0];
			
				if ( ( (fright >= 'a' && fright <= 'z') && sright == 0)){
					gramatica->production_function->productions[k].rightsimbols[1] = gramatica->production_function->productions[k].rightsimbols[0];
					gramatica->production_function->productions[k].rightsimbols[0] = 'M';
				}
			}
	}
	rotate_productions();
//	addProductions('M','/',-1);
	

}

void rotate_productions(){
	int k;
	
	for (k = 0; k < gramatica->production_function->size; k++){
			if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
				char left = gramatica->production_function->productions[k].leftsimbol;
				char sright = gramatica->production_function->productions[k].rightsimbols[1];
				char fright = gramatica->production_function->productions[k].rightsimbols[0];
			
				gramatica->production_function->productions[k].leftsimbol = fright;
				gramatica->production_function->productions[k].rightsimbols[0] = sright;
				gramatica->production_function->productions[k].rightsimbols[1] = left;
			}
	}
	gramatica->initial = 'M';
	addProductions('A','\\',0);
}
void left_normalize(){
	int j,k,i;
	
	for (k = 0; k < gramatica->production_function->size; k++){
			if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
				char left = gramatica->production_function->productions[k].leftsimbol;
				char sright = gramatica->production_function->productions[k].rightsimbols[1];
				char fright = gramatica->production_function->productions[k].rightsimbols[0];
			
				if ( ( (fright >= 'a' && fright <= 'z') && sright == 0)){
					gramatica->production_function->productions[k].rightsimbols[1] = 'M';
				}
			}
	}
	addProductions('M','\\',0);
	

}

void left_eliminateUnitaries(){
	int i,j,k;
	
	for (k = 0; k < gramatica->production_function->size; k++){
		if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
			char left = gramatica->production_function->productions[k].leftsimbol;
			char sright = gramatica->production_function->productions[k].rightsimbols[1];
			char fright = gramatica->production_function->productions[k].rightsimbols[0];
		
			if( fright >= 'A' && fright <= 'Z' && sright == 0){
				for (j = 0; j < gramatica->production_function->size; j++){
					if ( gramatica->production_function->productions[j].leftsimbol == fright ){
						char first_right = gramatica->production_function->productions[j].rightsimbols[0];
						char scnd_right = gramatica->production_function->productions[j].rightsimbols[1];
						addProductions(left,first_right,scnd_right);
					}
				}
					//Elimino la unitaria que está demas
					gramatica->production_function->productions[k].leftsimbol = 0;
			}
		
		}
	}
}
void eliminateUnreach(){
	int k,j,h;
	char * old = malloc(sizeof(char)*15);
	char * new = malloc(sizeof(char)*15);
	char newSymbol;
	//i=0;
	j=0;
	
	//old[i++] = gramatica->initial;
	new[j++] = gramatica->initial;
	
		for( h = 0; h < j; h++){
			newSymbol = new[h];
			for (k = 0; k < gramatica->production_function->size; k++){
				if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
					char left = gramatica->production_function->productions[k].leftsimbol;
					char sright = gramatica->production_function->productions[k].rightsimbols[1];
					char fright = gramatica->production_function->productions[k].rightsimbols[0];

					if ( left == newSymbol ){
						if( sright >= 'A' && sright <= 'Z'){
							if( !isContained(sright,new,j) ){
								new[j] = sright;
								j++;
							}
						}
						if( fright >= 'A' && fright <= 'Z'){
							if( !isContained(fright,new,j) ){
								new[j] = fright; 
								j++;
							}
						}
					}
				}
			}
		}
		
		for (k = 0; k < gramatica->production_function->size; k++){
			if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
				char left = gramatica->production_function->productions[k].leftsimbol;
				if ( !isContained(left,new,j) ){
					gramatica->production_function->productions[k].leftsimbol = 0;
				}
			}
		}
}

void eliminateInproductive(){
	int k,j,i;
	
	char * new = malloc(sizeof(char)*15);
	j=0;
	
	//Cargo los primeros;
		for (k = 0; k < gramatica->production_function->size; k++){
			if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
				char left = gramatica->production_function->productions[k].leftsimbol;
				char sright = gramatica->production_function->productions[k].rightsimbols[1];
				char fright = gramatica->production_function->productions[k].rightsimbols[0];
			
				if ( ( (fright >= 'a' && fright <= 'z') && sright == 0) || fright == '\\'){
					if ( !isContained(left,new,j) ){
						new[j] = left;
						j++;
					}
				}
			}
		}
	//Recorro a partir de los primeros para llegar a los que son productivos.	
	for( i = 0; i<j; i++){
		char newSymbol = new[i];
		for (k = 0; k < gramatica->production_function->size; k++){
				if ( gramatica->production_function->productions[k].leftsimbol != 0 ){
					char left = gramatica->production_function->productions[k].leftsimbol;
					char sright = gramatica->production_function->productions[k].rightsimbols[1];
					char fright = gramatica->production_function->productions[k].rightsimbols[0];
				
					if ( fright == newSymbol){
						if ( !isContained(left,new,j)){
							new[j] = left;
							j++;
						}
					}
					
					if ( sright == newSymbol){
						if ( !isContained(left,new,j)){
							new[j] = left;
							j++;
						}
					}
					
				}
		}			
	}
	
	//Elimino los que no estan contenidos en new o estan contenidos en inproductivos;
	char * inproductivos = malloc ( sizeof(char) * 15);
	int size = 0;
	for ( k = 0; k < gramatica->terminals->size; k++){
		if ( !isContained(gramatica->terminals->terminal[k], new, j) ){
			inproductivos[size] = gramatica->terminals->terminal[k];
			size++;
		}
	}
	
	for (k = 0; k < gramatica->production_function->size; k++){
		if ( gramatica->production_function->productions[k].leftsimbol != 0){
			char left = gramatica->production_function->productions[k].leftsimbol;
			char sright = gramatica->production_function->productions[k].rightsimbols[1];
			char fright = gramatica->production_function->productions[k].rightsimbols[0];
			
			if ( (isContained(fright,inproductivos,size) || isContained(sright,inproductivos, size) || isContained(left,inproductivos,size)) ){
				gramatica->production_function->productions[k].leftsimbol = 0;
			}
		}
	}	
	
}

int isContained(char left, char * new, int size){
	int i;
	
	for ( i = 0; i < size; i++){
		if ( left == new[i]){
			return 1;
		}
	}
	
	return 0;
	
}


void makeDotFile(FILE * file){
	int i,j,k;
	char * aux = malloc(gramatica->production_function->size * sizeof(char));
	int auxSize = 0;
	//Crear el archivo.
	file=fopen("file.dot","w");
	fseek(file, 0, SEEK_SET);
	//Insertar lineas.
	fputs("digraph{\n",file);
	//Inserta no terminales
	i=0;
	//Inserto Inicial
	fputs("node[shape=circle] ",file);
	fputc( gramatica->initial,file);
	fputs(" [label=\"",file);
	fputc((char)i+'0',file);
	fputs("\"];\n",file);
	i++;
		
	for (j = 0; j < gramatica->production_function->size; j++){
		char leftValue = gramatica->production_function->productions[j].leftsimbol;
		if ( leftValue != 0 &&  gramatica->production_function->productions[j].rightsimbols[0] != '\\' && leftValue != gramatica->initial && !isContained(leftValue,aux,auxSize)){
		aux[auxSize] = leftValue;
		auxSize++;
		fputs("node[shape=circle] ",file);
		fputc( leftValue,file);
		fputs(" [label=\"",file);
		fputc((char)i+'0',file);
		fputs("\"];\n",file);
		i++;
		}	
	}
	//Pongo los finales 
	for (j = 0; j < gramatica->production_function->size; j++){
		if ( gramatica->production_function->productions[j].leftsimbol != 0 &&  gramatica->production_function->productions[j].rightsimbols[0] == '\\'){
		
		fputs("node[shape=doublecircle] ",file);
		fputc( gramatica->production_function->productions[j].leftsimbol,file);
		fputs(" [label=\"",file);
		fputc((char)i+'0',file);
		fputs("\"];\n",file);
		i++;
		}	
	}
	
	
	//Transiciones
	for (k = 0; k < gramatica->production_function->size; k++){
		if ( gramatica->production_function->productions[k].leftsimbol != 0 &&  gramatica->production_function->productions[k].rightsimbols[0] != '\\'){
			char left = gramatica->production_function->productions[k].leftsimbol;
			char right = gramatica->production_function->productions[k].rightsimbols[1];
			char label = gramatica->production_function->productions[k].rightsimbols[0];
			fputc(left,file);
			fputs("->",file);
			fputc(right,file);
			fputs(" [label=\"",file);
			fputc(label,file);
			fputs("\"];\n",file);	
			i++;	
		}
	}
	fputs("}\n",file);
	
	return;
	
}


int createGramatica(){
	
	gramatica=malloc(sizeof(gramatica_struct));
	if (gramatica == NULL)
		return 0;
	return initializeFunctions() && initializeNonTerminals() && initializeTerminals();
}

int initializeFunctions(){
	gramatica->production_function =malloc(sizeof(production_function_struct));
	if(gramatica->production_function == NULL)
	return 0;
	gramatica->production_function->productions=NULL;
	gramatica->production_function->size=0;
	return 1;
}

int initializeNonTerminals(){
	gramatica->nonterminals = malloc(sizeof(nonterminals_struct));
	if(gramatica->nonterminals == NULL)
	return 0;
	gramatica->nonterminals->nonterminals =NULL;
	gramatica->nonterminals->size=0;
	return 1;
}

int initializeTerminals(){
	gramatica->terminals =malloc(sizeof(terminals_struct));
	if(gramatica->terminals == NULL)
	return 0;
	gramatica->terminals->terminal=NULL;
	gramatica->terminals->size=0;
	return 1;
}
void reportError(char* errorMsg, char* token){

	printf("Se produjo un error tratando de leer %s cuando se leyo %s\n",errorMsg,token);
	exit(0);

}

int addTerminal(char c){
	int size = gramatica->terminals->size;
	if(size%BLOCK==0)
		gramatica->terminals->terminal=realloc(gramatica->terminals->terminal,(size+BLOCK)*sizeof(char));	
	gramatica->terminals->terminal[size] = c;
	gramatica->terminals->size = size+1;
	return 1;
}

int addNonTerminal(char c){
	int size = gramatica->nonterminals->size;
	if(size%BLOCK ==0)
		gramatica->nonterminals->nonterminals=realloc(gramatica->nonterminals->nonterminals,(size+BLOCK)*sizeof(char));
	gramatica->nonterminals->nonterminals[size] = c;
	gramatica->nonterminals->size = ++size;
	return 1;
}

int addInitialSymbol(char  c){
	gramatica->initial = c;
	return 1;
}

void getProductionLeftPart(char c){
	leftPart=c;
}

int getProduction(char* c,int lenght){
	int i=0;
	int size=gramatica->production_function->size;
	if(size%BLOCK==0)
		gramatica->production_function->productions=realloc(gramatica->production_function->productions, (size+BLOCK)*sizeof(production_struct));
	gramatica->production_function->productions[size].leftsimbol=leftPart;
	
	gramatica->production_function->productions[size].rightsimbols=malloc(lenght*sizeof(char));
	
	for(i=0;i< lenght;i++)
		gramatica->production_function->productions[size].rightsimbols[i]=c[i];
	gramatica->production_function->productions[size].rightsimbolslenght=lenght;
	gramatica->production_function->size=size+1;
	return 1;
		
}

void showTerminalSymbols(){
	int i;
	printf("Simbolos Terminales\n");
	for( i = 0; i < gramatica->terminals->size; i++){
		printf("%c\n", gramatica->terminals->terminal[i]);

	}
	printf("End\n\n");
}

void showNonTerminalSymbols(){
	int i;
	printf("Simbolos No Terminales\n");
	for( i = 0; i < gramatica->nonterminals->size; i++){
		printf("%c\n", gramatica->nonterminals->nonterminals[i]);

	}
	printf("End\n\n");
}


void showInitialSymbol(){

	printf("Simbolo Inicial\n");
	printf("%c\n", gramatica->initial);
	printf("End\n\n");
}

void showProductionSymbols(){
	int i;
	printf("Producciones\n");
	for( i = 0; i < gramatica->production_function->size; i++){
		if(gramatica->production_function->productions[i].leftsimbol != 0){
			printf("%c -> %c%c\n", gramatica->production_function->productions[i].leftsimbol, gramatica->production_function->productions[i].rightsimbols[0],gramatica->production_function->productions[i].rightsimbols[1]);
		}
	}
	printf("End\n\n");
}





 
